- modules/operations/pages/astream-regions.adoc
- modules/operations/pages/astream-release-notes.adoc
Add australia-east region, and update release notes with latest changes (transforms, transactions, new region).
* https://datastax.jira.com/browse/AS-1667
* https://datastax.jira.com/browse/AS-1694
* https://datastax.jira.com/browse/AS-1695
* https://datastax.jira.com/browse/AS-1696
> releasenotes-and-regions

- modules/developing/pages/astream-kafka.adoc
Replace "boo" S4K example with "hello pulsar".
> remove-boo

- antora.yml
astra-streaming-examples-repo: 'https://raw.githubusercontent.com/dddieruf/astra-streaming-examples/master' 
to 
astra-streaming-examples-repo: 'https://raw.githubusercontent.com/datastax/astra-streaming-examples/master'
> astra-streaming-examples-repo

- modules/developing/nav.adoc
- modules/developing/pages/astra-cli.adoc
- modules/getting-started/pages/index.adoc
* Add page to redirect users to astra-cli-docs.
* Clarify Astra-CLI's utility in Getting Started per Yabin.
> Doc 3525 develop an astra cli overview page for astra streaming docs

- modules/ROOT/pages/astream-faq.adoc
- modules/operations/pages/astream-limits.adoc
> Dedicated cluster limits

- modules/ROOT/nav.adoc
- modules/operations/nav.adoc
- modules/operations/pages/astream-release-notes.adoc
* WH release notes and nav.
* Coppi build : https://coppi.aws.dsinternal.org/streaming-docs/welcome-home-release-notes/astra-streaming/operations/astream-release-notes.html
> welcome-home

- modules/operations/pages/astream-token-gen.adoc
More info on AS token gen.
https://coppi.aws.dsinternal.org/streaming-docs/astra-streaming-tokens/astra-streaming/operations/astream-token-gen.html
> Token gen 2

- modules/developing/pages/astream-functions.adoc
- modules/operations/pages/astream-limits.adoc
Users now need a qualified org to create custom functions.
> custom-functions-update

- modules/operations/nav.adoc
- modules/operations/pages/private-connectivity.adoc
Add page detailing private connectivity in AS. 
Coppi build: https://coppi.aws.dsinternal.org/en/streaming/astra-streaming/operations/private-connectivity.html
> As 2367 astra streaming support for private connectivity

- modules/operations/pages/astream-regions.adoc
- modules/operations/pages/astream-release-notes.adoc
Release notes and page for new regions: 
AWS - ap-south-1 
AWS - ap-southeast-1 
AWS - eu-central-1 
AWS - eu-west-1 
Azure - westeurope 
Azure - eastus2
> Regions Update and Release Notes

- modules/ROOT/nav.adoc
- modules/operations/pages/astream-release-notes.adoc
Change "Release Notes" to "Changelog".
> Change release notes to changelog

- modules/operations/pages/astream-regions.adoc
- modules/operations/pages/astream-release-notes.adoc
> add-aws-euwest-1

- modules/operations/pages/astream-regions.adoc
- modules/operations/pages/astream-release-notes.adoc
Azure westeurope and release note.
> Stage new regions

- modules/operations/pages/astream-regions.adoc
- modules/operations/pages/astream-release-notes.adoc
> Stage to main

- modules/langstream/pages/index.adoc
Reflect recent application changes and testing.
> Langstream update

- modules/ragstack/pages/quickstart.adoc
Add google-client-id to secrets and a note for creating one.
> google-client-id secret

- antora.yml
> hide-ragstack

- .github/workflows/dispatch-deploy-draft.yml
This pull request contains updates to support the unified build.
> Updates for unified build

- antora.yml
- modules/ROOT/nav.adoc
- modules/operations/nav.adoc
- modules/operations/pages/astream-release-notes.adoc
* Apply the new release notes format
* Move the release notes and FAQ topics to the appropriate position in the nav.
https://d5rxiv0do0q3v.cloudfront.net/doc-4637-streaming/astra-streaming/operations/astream-release-notes.html
> DOC-4637 Astra Streaming release notes format

- modules/operations/pages/private-connectivity.adoc
Remove outdated private link admonition.
> docs: remove-outdated-admonition

- modules/developing/pages/astream-cdc.adoc
Break the CDC partial into multiple smaller partials by heading.
* Common: https://github.com/riptano/docs-common/pull/32 
* Serverless: https://github.com/riptano/astra-vector-docs/pull/955 
* Streaming: https://github.com/datastax/astra-streaming-docs/pull/131
> DOC-5158 - break cdc into multiple partials (streaming)
